version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql